version: "3.8"

services:
  ms-continuus:
    depends_on:
      - storage-emulator

  storage-emulator:
    image: mcr.microsoft.com/azure-storage/azurite
    volumes:
      - "./blobStorage:/data"
    ports:
      - "10000:10000" # Blobs
    command: ["azurite","--blobHost", "0.0.0.0"]
