version: "3.8"

services:
  ms-continuus:
    environment:
      # Uses the default azurite storage account
      # For more information, see https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#authorize-with-shared-key-credentials
      STORAGE_KEY: "\
        UseDevelopmentStorage=true;\
        BlobEndpoint=http://storage-emulator:10000/devstoreaccount1;\
        "
    depends_on:
      - storage-emulator
    env_file:
      - .env

  storage-emulator:
    image: mcr.microsoft.com/azure-storage/azurite
    volumes:
      - "blobStorage:/data"
    ports:
      - "10000:10000"  # Blobs
    command: [
        "azurite",
        "--blobHost", "0.0.0.0",
        "--oauth", "basic",
    ]

volumes:
  blobStorage: {}
