version: "3.4"

services:

  app:
    build:
      context: .
    environment:
      GITHUB_ORG: equinor-test
      BLOB_TAG: weekly
      BLOB_CONTAINER: github-archives
      WEEKLY_RETENTION: 1
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      STORAGE_KEY: ${STORAGE_KEY}
