version: "3.4"

services:

  ms-continuus:
    image: sdpequinor/ms-continuus
    build:
      context: .
    environment:
      GITHUB_ORG: equinor
      BLOB_TAG: weekly
      BLOB_CONTAINER: github-archives
      WEEKLY_RETENTION: 1
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      STORAGE_KEY: ${STORAGE_KEY}
