version: "3.8"

services:
  ms-continuus:
    depends_on:
      - storage-emulator

  storage-emulator:
    image: mcr.microsoft.com/azure-storage/azurite
    volumes:
      - "./blobStorage:/data"
    ports:
      - "10000:10000"
    command: ["azurite","--blobHost", "0.0.0.0", "--location", "/data"]

  mock-api:
    build: mock_api
    volumes:
      - ./mock_api:/app
    ports:
      - "5000:5000"
    command: "python /app/mock_gh_api.py"
