name: Publish Docker image
on:
  push:
    branches: [main]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker login
        run: echo ${{ secrets.GH_REGISTRY }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Pull latest
        run: docker pull ghcr.io/equinor/ms-continuus:main
      - name: Build
        run: docker build . --tag ghcr.io/equinor/ms-continuus:main --cache-from ghcr.io/equinor/ms-continuus:main
      - name: Push
        run: docker push ghcr.io/equinor/ms-continuus:main
